const mongoose = require("mongoose");

const Kyc = mongoose.model("kyc", {
  emp_id: String,
  name: String,
  phone: String,
  email: String,
  dob: String,
  gender: String,
  source: String,
  employment: String,
  org: String,
  annual: String,
  marital: String,
  details: String,
  nature: String,
  dop: String,
  uploadbill: String,
  current: String,
  office: String,
  landmark: String,
  residential: String,
  chooseId: String,
  idNo: String,
  uploadId: String,
  chooseAdd: String,
  addressNo: String,
  uploadAdd: String,
  stonewaste: String,
  bankName: String,
  acNo: String,
  ifsc: String,
  branch: String,
  how: String,
  tv: String,
  photo: String,
  today: String,
  status: String,
  time: String,
  release_amount: String,
  payment_type: String,
  bill_type: String,
  margin: String,
  sendingDate: String,
});

export default Kyc;
